### ISSUE TITLE
Multiple instances of same bookmark

### ISSUE THREAD

**Issue by FilipKendes** [nortmas/chrome-bookmarks#10]
This is my first issue report, so I don't know what info I need to provide.
 
I have an issue when I search for bookmark it shows me multiple instances of the same bookmark. 
I'm using brave browser latest version and latest ulauncher from aur (version 5.9.0-1).

![Screenshot_20201210_163522](https://user-images.githubusercontent.com/34419647/101793698-60836b00-3b06-11eb-8c5f-accc330d5f20.png)
![Screenshot_20201210_163719](https://user-images.githubusercontent.com/34419647/101793728-65e0b580-3b06-11eb-9a5f-2885f4b9a8c5.png)

**Comment by nortmas** [comment]
I could not reproduce the issue in chrome browser
This extension was designed to work with the Chrome browser. The Chrome-based browsers were added to the list but were never properly tested. 
I'm sorry but I don't have time to support all variations of the Chrome browsers.

**Comment by AlexNabokikh** [comment]
@FilipKendes there is a chance that this is not the plugin problem. It may happen if you symlink your .config directory from your dotfiles to the home dir. You can check it by using `locate Brave-Browser | grep Bookmarks`
