### ISSUE TITLE
Improve Docs > Extension requires locate utility

### ISSUE THREAD

**Issue by pascalbe-dev** [nortmas/chrome-bookmarks#11]
I ran into an issue, that the extension should not find any bookmarks. In the end I looked through the code and found out, that the extension relies on the locate command, which requires the mlocate utility to be installed on the system. This was not the case for me (ubuntu focal fossa minimal installation). 

## Request

The docs should note all the requirements necessary to run the extension successfully. This will make it easier for others get it working.

`sudo apt install -y mlocate`

**Comment by nortmas** [comment]
Thanks, good point.
