### ISSUE TITLE
Bug > bookmark search does not work with capital letters in bookmark

### ISSUE THREAD

**Issue by pascalbe-dev** [nortmas/chrome-bookmarks#13]
## Current behavior

When I search for a bookmark starting with a capital letter, the search won't find any results.
E.g.:
* bookmark name: Jenkins UI
* search term: Jenkins

--> no results

## Desired behavior

The extension can find all bookmark case insensitively.

**Comment by nortmas** [comment]
Fixed. Also found one more bug and fixed it. Now it should work much better.

**Comment by pascalbe-dev** [comment]
Nice. Works! 
Thanks for the quick fix :)
