### ISSUE TITLE
Does not work with Brave bookmarks

### ISSUE THREAD

**Issue by dtrossiter** [nortmas/chrome-bookmarks#14]
Seems to recognize the keyword (bb), but does not find any matching bookmarks. I verified that mlocate is installed. Not sure what I'm doing wrong. I don't see any options or switches to tell it I'm using Brave. Any suggestions?

Brave Version 1.24.84 Chromium: 90.0.4430.93 (Official Build) (64-bit)

uname -a (Linux Mint 20.1)
Linux david 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

inxi
CPU: 8-Core AMD Ryzen 7 3700X (-MT MCP-) speed/min/max: 2192/2200/3600 MHz 
Kernel: 5.8.0-53-generic x86_64 Up: 26m Mem: 5667.0/32119.8 MiB (17.6%) 
Storage: 953.87 GiB (21.3% used) Procs: 427 Shell: bash 5.0.17 inxi: 3.0.38

**Comment by nortmas** [comment]
Hello, 

in the plugin description I've mentioned the following:

_This extension was developed for personal usage and tested on Ubuntu 20.04 LTS and Chrome browser. I've also added the 'Chromium' and 'Brave' browser to the bookmark search list but unfortunately, I don't have time to support and test all browsers and Linux distribution variations so you might face bugs. If you have an issue in your chromium based browser/Linux combination feel free to investigate and come up with the patch and please create issues only related to the Ubuntu and Chrome browser combination._

**Comment by dtrossiter** [comment]
I did not ask you add support for Brave. You say Brave is already supported. So, it simply does not work. That's a shame.
