### ISSUE TITLE
Not compatible with the latest version of Ulauncher

### ISSUE THREAD

**Issue by ghost** [nortmas/chrome-bookmarks#4]
![image](https://user-images.githubusercontent.com/37113869/62413942-f818a580-b604-11e9-8c3e-c0a99be0b2af.png)

**Comment by pascalbe-dev** [comment]
Can not reproduce. Works for me with the latest ulauncher version.

- ulauncher: 5.9.0
- extension api: 2.0.0

**Comment by nortmas** [comment]
Me neither. Guess we can close it.
