### ISSUE TITLE
Doesn't work on Manjaro

### ISSUE THREAD

**Issue by level39** [nortmas/chrome-bookmarks#7]
File "~/.local/share/ulauncher/extensions/com.github.nortmas.chrome-bookmarks/ChromeBookmarks.py", line 86, in get_items

```
for bookmark in matches:
TypeError: 'NoneType' object is not iterable
```
Meaning it's found the bookmarks file but is not parsing it properly.

Browser: Chromium Version 83.0.4103.61 (Official Build) Arch Linux (64-bit)

**Comment by nortmas** [comment]
Could not reproduce.

**Comment by nortmas** [comment]
Sorry, I'm not supporting all the variations of the Linux distribution.
