### ISSUE TITLE
Add "other" category to results

### ISSUE THREAD

**Issue by sbeugen** [nortmas/chrome-bookmarks#9]
Currently only "bookmark_bar" part of the bookmarks is considered when doing the lookup.
Chrome also has the "other" category.

So the part of your code should look like follows.
Current:
```
                data = json.load(data_file)
                bookmark_bar = data['roots']['bookmark_bar']
                matches = self.find_rec(bookmark_bar, query, matches)
```

Should be:
```
                data = json.load(data_file)
                bookmark_bar = data['roots']['bookmark_bar']
                other = data['roots']['other']
                self.find_rec(other, query, matches)
                matches = self.find_rec(bookmark_bar, query, matches)
```

If you want, I can also create a PR.

**Comment by nortmas** [comment]
Hi, I've deployed your change, yes feel free to create a PR. 
Sorry, currently I don't have much time to maintain it :(

**Comment by sbeugen** [comment]
Thx :+1:

**Comment by nortmas** [comment]
Code refatored. Issue fixed.
